# Generated by Django 5.1.6 on 2025-02-19 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_customer_completename_alter_customer_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_store',
            field=models.BooleanField(default=False),
        ),
    ]
