# Generated by Django 5.1.6 on 2025-02-19 02:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_customer_is_store'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='part_images/')),
                ('brand', models.CharField(choices=[('Toyota', 'Toyota'), ('Mitsubishi', 'Mitsubishi'), ('Honda', 'Honda'), ('Nissan', 'Nissan'), ('Ford', 'Ford'), ('Isuzu', 'Isuzu'), ('Hyundai', 'Hyundai'), ('Kia', 'Kia'), ('Chevrolet', 'Chevrolet'), ('Suzuki', 'Suzuki'), ('Mazda', 'Mazda'), ('Subaru', 'Subaru'), ('Fuso', 'Fuso'), ('Hino', 'Hino'), ('Tata', 'Tata'), ('MAN', 'MAN'), ('Scania', 'Scania'), ('Volkswagen', 'Volkswagen'), ('Chery', 'Chery'), ('Foton', 'Foton'), ('JAC', 'JAC'), ('Dongfeng', 'Dongfeng'), ('Changan', 'Changan'), ('Geely', 'Geely'), ('MG', 'MG'), ('BYD', 'BYD'), ('BAIC', 'BAIC'), ('GAC', 'GAC'), ('Maxus', 'Maxus')], max_length=255)),
                ('year', models.PositiveIntegerField()),
                ('car_model', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
