# Generated by Django 5.1.6 on 2025-02-19 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_rename_image_partrequest_image1_partrequest_image2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='completename',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='partrequest',
            name='brand',
            field=models.CharField(choices=[('Toyota', 'Toyota'), ('Mitsubishi', 'Mitsubishi'), ('Honda', 'Honda'), ('Nissan', 'Nissan'), ('Ford', 'Ford'), ('Isuzu', 'Isuzu'), ('Hyundai', 'Hyundai'), ('Kia', 'Kia'), ('Chevrolet', 'Chevrolet'), ('Suzuki', 'Suzuki'), ('Daihatsu', 'Daihatsu'), ('Mazda', 'Mazda'), ('Subaru', 'Subaru'), ('Fuso', 'Fuso'), ('Hino', 'Hino'), ('Tata', 'Tata'), ('MAN', 'MAN'), ('Scania', 'Scania'), ('Volkswagen', 'Volkswagen'), ('Chery', 'Chery'), ('Foton', 'Foton'), ('JAC', 'JAC'), ('Dongfeng', 'Dongfeng'), ('Changan', 'Changan'), ('Geely', 'Geely'), ('MG', 'MG'), ('BYD', 'BYD'), ('BAIC', 'BAIC'), ('GAC', 'GAC'), ('Maxus', 'Maxus')], max_length=255),
        ),
    ]
