# Generated by Django 5.1.6 on 2025-02-19 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_customer_completename_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partrequest',
            name='orderdate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
