# Generated by Django 5.1.6 on 2025-02-19 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_partrequest_orderdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partrequest',
            name='orderdate',
        ),
        migrations.AddField(
            model_name='partrequest',
            name='brand_new',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='partrequest',
            name='used',
            field=models.BooleanField(default=True),
        ),
    ]
