# Generated by Django 5.1.6 on 2025-02-19 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_remove_partrequest_orderdate_partrequest_brand_new_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partrequest',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], default='Open', max_length=10),
        ),
        migrations.AlterField(
            model_name='partrequest',
            name='brand_new',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='partrequest',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
