# Generated by Django 5.1.6 on 2025-02-19 06:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='bid_images/'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
