# Generated by Django 5.1.6 on 2025-02-19 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_bid_image1_alter_bid_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='partrequest',
            name='qty',
            field=models.PositiveIntegerField(default='1'),
        ),
    ]
