# Generated by Django 5.1.6 on 2025-02-19 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_partrequest_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='condition',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Brand New', max_length=10),
        ),
    ]
