# Generated by Django 5.1.6 on 2025-02-19 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_bid_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='condition',
            field=models.CharField(choices=[('New', 'Brand New'), ('Used', 'Used')], default='Brand New', max_length=10),
        ),
    ]
