# Generated by Django 5.1.6 on 2025-02-19 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_alter_bid_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='condition',
            field=models.CharField(choices=[('Brand New', 'Brand New'), ('Used', 'Used')], default='Brand New', max_length=10),
        ),
        migrations.AlterField(
            model_name='bid',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='', max_length=10),
        ),
    ]
