# Generated by Django 5.1.6 on 2025-03-18 03:05

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_alter_bid_condition_alter_bid_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='image1',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='bid_images/'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='image2',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='bid_images/'),
        ),
        migrations.AlterField(
            model_name='partrequest',
            name='image1',
            field=models.ImageField(storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='part_images/'),
        ),
        migrations.AlterField(
            model_name='partrequest',
            name='image2',
            field=models.ImageField(storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='part_images/'),
        ),
    ]
