# Generated by Django 5.0.4 on 2026-06-01 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_alter_bid_image1_alter_bid_image2_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bid',
            options={'ordering': ['status', '-price']},
        ),
    ]
