# Generated by Django 5.0.4 on 2026-06-02 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_alter_bid_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='partrequest',
            name='qty',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
